---
- hosts: servers
  remote_user: "{{ username }}"
  tasks:
    - name: Print all available facts
      debug:
        var: ansible_facts
    - name: Print {{ ansible_distribution_release }}
      debug:
        var: ansible_distribution_release
    - name: Print architecture
      debug:
        var: ansible_facts['architecture']
    - name: Print version
      debug:
        var: ansible_facts['lsb']['release']