---
- hosts: desktops
  remote_user: "{{ username }}"
  tasks:
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts
    - name: Print {{ ansible_distribution_release }}
      ansible.builtin.debug:
        var: ansible_distribution_release