ARG PYTHON_VERSION=latest
FROM python:$PYTHON_VERSION-slim-buster
# Setup PIP and Ansible
RUN pip install pip --upgrade
COPY requirements.txt .
RUN pip install -r requirements.txt
RUN pip freeze > requirements.txt
RUN cat requirements.txt